import Head from "next/head";
import Image from "next/image";
import { Inter } from "next/font/google";
import styles from "@/styles/Home.module.css";

const inter = Inter({ subsets: ["latin"] });

export default function Home() {
  return (
    <>
      <Head>
        <title>Events App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <header></header>
      <nav>
        <img />
        <a href="/">Home</a>
        <a href="/events">Events</a>
        <a href="/aboutUs">About Us</a>
      </nav>
      <main className={styles.main}>
        <a href="">
          <div>
            <img src="" alt="" />
            <h2>Events in London</h2>
            <p>
              Lorem ipsum dolor sit amet, consectetur adipisicing elit. Quos,
              similique laborum, exercitationem qui rem quod ea assumenda
              dolores doloribus iste consequuntur deserunt facere! Doloribus
              itaque accusantium ratione eveniet iste provident.
            </p>
          </div>
        </a>
        <a href="">
          <div>
            <img src="" alt="" />
            <h2>Events in San Francisco</h2>
            <p>
              Lorem ipsum dolor sit amet, consectetur adipisicing elit. Quos,
              similique laborum, exercitationem qui rem quod ea assumenda
              dolores doloribus iste consequuntur deserunt facere! Doloribus
              itaque accusantium ratione eveniet iste provident.
            </p>
          </div>
        </a>
        <a href="">
          <div>
            <img src="" alt="" />
            <h2>Events in San Bacelona</h2>
            <p>
              Lorem ipsum dolor sit amet, consectetur adipisicing elit. Quos,
              similique laborum, exercitationem qui rem quod ea assumenda
              dolores doloribus iste consequuntur deserunt facere! Doloribus
              itaque accusantium ratione eveniet iste provident.
            </p>
          </div>
        </a>
      </main>
    </>
  );
}
